name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install glut
      run: sudo apt update && sudo apt install freeglut3-dev
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: makeplaterbuild
      working-directory: plater
      run: mkdir build
    - name: cmake
      working-directory: plater/build
      run: cmake ..
    - name: makeplater
      working-directory: plater/build
      run: make
    - name: qmake
      working-directory: gui/build
      run: qmake ..
    - name: make
      working-directory: gui/build
      run: make
    - name: install
      working-directory: gui/build
      run: sudo make install
