name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: makebuilddir
      run: mkdir gui/build
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: qmake
      working-directory: gui/build
      run: qmake ..
    - name: make
      working-directory: gui/build
      run: make
    - name: install
      working-directory: gui/build
      run: sudo make install
