name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: makebuilddir
      run: mkdir gui/build
    - name: cdtogui
      run: cd gui/build
    - name: qmake
      run: qmake ..
    - name: make
      run: make
    - name: install
      run: sudo make install
